apiVersion: apps/v1
kind: Deployment
metadata:
  name: guess-game-deployment
  labels:
    app: guess-game
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guess-game
  template:
    metadata:
      labels:
        app: guess-game
    spec:
      containers:
        - name: guess-game
          image: adah001/guess-game:21
          ports:
            - containerPort: 3000  # change if your app listens on another port
          imagePullPolicy: Always
